language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8 ./src
  - python3 ./src/books/manage.py check
  - python3 ./src/books/manage.py makemigrations --check --dry-run