# Generated by Django 2.2.16 on 2020-10-30 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='user.User'),
        ),
    ]
