# Generated by Django 2.2.16 on 2020-10-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20201030_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users',
        ),
    ]
